plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

remote_theme: jekyll/minima

minima:
  skin: dark

# Navigation nur für Bear Trap setzen
header_pages:
  - GUIDE_EN.md
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      hide_title: true
  

# Bestimmte Dateien NICHT in die Navigation aufnehmen
exclude:
  - README.md
  - GUIDE_AR.md
  - GUIDE_DE.md
  - GUIDE_ES.md
  - GUIDE_FR.md
  - GUIDE_RU.md
